name: rick_and_morty_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  cached_network_image: ^3.4.1
  mobx: ^2.3.3+2
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  sizzle_lints: ^2.1.3
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3
  drift_dev: ^2.21.0
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true
