import 'package:flutter/widgets.dart';

/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData alien = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alive = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liked = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dead = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData human = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unknown_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unliked = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_unknown = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
